apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |
    - op: replace
      value: manifests/overlays/prod/kustomization.yaml
      path: /spec/generators/0/scmProvider/filters/0/pathsExist/0
      # path: /spec/template/metadata/name
    - op: replace
      value: manifests/overlays/prod
      path: /spec/template/spec/source/path
  target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: platform|customers
