  apiVersion: container.cnrm.cloud.google.com/v1beta1
  kind: ContainerCluster
  metadata:
    name: customer
  spec:
    description: customer cluster
    location: australia-southeast1-a
    initialNodeCount: 1
    networkingMode: ROUTES
    addonsConfig:
      configConnectorConfig:
        enabled: true
      httpLoadBalancing:
        disabled: false
    workloadIdentityConfig:
      # Replace david-brownbag with your project ID.
      workloadPool: "david-brownbag.svc.id.goog"
