  apiVersion: container.cnrm.cloud.google.com/v1beta1
  kind: ContainerCluster
  metadata:
    name: customer
    annotations:
      cnrm.cloud.google.com/project-id: david-brownbag
  spec:
    description: An autopilot cluster.
    enableAutopilot: true
    location: australia-southeast1
    addonsConfig:
      configConnectorConfig:
        enabled: true
      httpLoadBalancing:
        enabled: true
    releaseChannel:
      channel: REGULAR

