apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customer-a
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/DavidSourcedTestOrg/customer-a'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
